# Generated by Django 6.0.1 on 2026-01-13 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Userinfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=32)),
                ("Account", models.CharField(max_length=32)),
                ("password", models.CharField(max_length=64)),
                ("age", models.IntegerField(default=2)),
                ("email", models.EmailField(max_length=254)),
                ("gender", models.CharField(default="unknown", max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="PersonalPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="照片标题")),
                (
                    "image",
                    models.ImageField(
                        upload_to="personal_photos/%Y/%m/", verbose_name="照片文件"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="照片描述")),
                ("taken_date", models.DateField(verbose_name="拍摄日期")),
                ("location", models.CharField(max_length=200, verbose_name="拍摄地点")),
                (
                    "camera",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="拍摄设备"
                    ),
                ),
                (
                    "tags",
                    models.CharField(blank=True, max_length=300, verbose_name="标签"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("travel", "旅行"),
                            ("family", "家庭"),
                            ("friends", "朋友"),
                            ("nature", "自然"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="分类",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.userinfo",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "个人照片",
                "verbose_name_plural": "个人照片",
                "ordering": ["-taken_date"],
            },
        ),
    ]
